ALTER TABLE SUPER_APPLICATION_USER ADD INITLOGIN_DONE CHAR(1) DEFAULT 'N';
ALTER TABLE APPLICATION_USER ADD INITLOGIN_DONE CHAR(1) DEFAULT 'N';

alter table pm_parameter_config alter column list_values text;
