alter table APPLICATION_USER add created_date datetime;
alter table APPLICATION_USER add last_updated_by bigint;
alter table APPLICATION_USER add last_updated datetime;
alter table APPLICATION_USER add created_by  bigint;
alter table APPLICATION_USER add displayname varchar(255);
alter table APPLICATION_USER add hide_splash boolean;
alter table APPLICATION_USER add last_logged_time bigint;
alter table APPLICATION_USER add auth_handler_id bigint;
alter table APPLICATION_USER add email varchar(255);	
alter table DEVELOPMENT_ENTITIES add extended_desc longtext;	
alter table SUPER_APPLICATION_USER add created_date datetime;
alter table SUPER_APPLICATION_USER add last_updated_by bigint;
alter table SUPER_APPLICATION_USER add last_updated datetime;
alter table SUPER_APPLICATION_USER add created_by bigint;
alter table SUPER_APPLICATION_USER add displayname varchar(255);
alter table SUPER_APPLICATION_USER add hide_splash boolean;
alter table SUPER_APPLICATION_USER add last_logged_time bigint;
alter table SUPER_APPLICATION_USER add email varchar(255);
create table APP_USER_PROPERTIES (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,data_type varchar(255),prop_key varchar(255),super_user_id bigint,user_id bigint,prop_value varchar(255),primary key (id));
create table AUDIT_LOGS (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,component varchar(1000),hidden boolean,msgCode varchar(255),msgParams varchar(3000),primary key (id));	
create table AUTH_HANDLER_REGISTRY (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,account_id varchar(255),config_data_json longtext,name varchar(255),type varchar(255),user_attrs_json longtext,primary key (id));
create table DEVELOPMENT_ENTITIES_TAGS (dev_entity_id bigint not null,tag_id bigint not null,primary key (dev_entity_id, tag_id));
create table OPERATOR_CONFIG (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,data_type varchar(255),operator_key varchar(255),label varchar(255),primary key (id));
create table PM_ACTION_CONFIG (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,name varchar(255),short_code varchar(2),short_name varchar(50),plcy_model_id bigint,primary key (id));
create table PM_ATTRIBUTE_CONFIG (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,data_type varchar(255),name varchar(255),reg_ex_pattern varchar(255),short_name varchar(50),policy_model_id bigint,plcy_model_id bigint,primary key (id));
create table PM_ATTRIB_CONFIG_OPER_CONFIG (attribute_id bigint not null,operator_id bigint not null,primary key (attribute_id, operator_id));
create table PM_OBLIGATION_CONFIG (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,name varchar(255),run_at varchar(255),short_name varchar(50),plcy_model_id bigint,primary key (id));
create table PM_PARAMETER_CONFIG (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,default_value varchar(1000),is_editable boolean,is_hidden boolean,list_values varchar(1000),is_mandatory boolean,name varchar(255),short_name varchar(50),data_type varchar(255),obligation_id bigint,primary key (id));
create table POLICY_MODEL (discriminator varchar(31) not null,id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,description varchar(4000),name varchar(264),short_name varchar(50),status varchar(255),type varchar(255),primary key (id));
create table POLICY_MODEL_TAGS (plcy_model_id bigint not null,tag_id bigint not null,primary key (plcy_model_id, tag_id));
create table SAVED_SEARCH (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,criteria_json varchar(4000),description varchar(255),lowercase_name varchar(255),name varchar(255),shared_mode varchar(255),status varchar(255),type varchar(255),primary key (id));
create table TAG_LABELS (id bigint not null auto_increment,created_date datetime,last_updated_by bigint,last_updated datetime,created_by bigint,version integer not null,hidden boolean,tag_key varchar(255),label varchar(255),status varchar(255),type varchar(255),primary key (id));
alter table APP_USER_PROPERTIES add index FK87A05FE9B53FEACB (super_user_id), add constraint FK87A05FE9B53FEACB foreign key (super_user_id) references SUPER_APPLICATION_USER (id);
alter table APP_USER_PROPERTIES add index FK87A05FE9A759120A (user_id), add constraint FK87A05FE9A759120A foreign key (user_id) references APPLICATION_USER (id);
alter table DEVELOPMENT_ENTITIES_TAGS add index FKDB1ED5B379C3E7F9 (dev_entity_id), add constraint FKDB1ED5B379C3E7F9 foreign key (dev_entity_id) references DEVELOPMENT_ENTITIES (id);
alter table DEVELOPMENT_ENTITIES_TAGS add index FKDB1ED5B3E3AB049A (tag_id), add constraint FKDB1ED5B3E3AB049A foreign key (tag_id) references TAG_LABELS (id);
alter table PM_ACTION_CONFIG add index FKEC9D56A94476BBF5 (plcy_model_id), add constraint FKEC9D56A94476BBF5 foreign key (plcy_model_id) references POLICY_MODEL (id);
alter table PM_ATTRIBUTE_CONFIG add index FK85828674476BBF5 (plcy_model_id), add constraint FK85828674476BBF5 foreign key (plcy_model_id) references POLICY_MODEL (id);
alter table PM_ATTRIBUTE_CONFIG add index FK8582867B27E9A35 (policy_model_id), add constraint FK8582867B27E9A35 foreign key (policy_model_id) references POLICY_MODEL (id);
alter table PM_ATTRIB_CONFIG_OPER_CONFIG add index FK2AB580A9FC12A4DC (operator_id), add constraint FK2AB580A9FC12A4DC foreign key (operator_id) references OPERATOR_CONFIG (id);
alter table PM_ATTRIB_CONFIG_OPER_CONFIG add index FK2AB580A965AE0D5C (attribute_id), add constraint FK2AB580A965AE0D5C foreign key (attribute_id) references PM_ATTRIBUTE_CONFIG (id);
alter table PM_OBLIGATION_CONFIG add index FK70C823614476BBF5 (plcy_model_id), add constraint FK70C823614476BBF5 foreign key (plcy_model_id) references POLICY_MODEL (id);
alter table PM_PARAMETER_CONFIG add index FK79C446BAFD78E31C (obligation_id), add constraint FK79C446BAFD78E31C foreign key (obligation_id) references PM_OBLIGATION_CONFIG (id);
alter table POLICY_MODEL_TAGS add index FKDC8BC8BC4476BBF5 (plcy_model_id), add constraint FKDC8BC8BC4476BBF5 foreign key (plcy_model_id) references POLICY_MODEL (id);
alter table POLICY_MODEL_TAGS add index FKDC8BC8BCE3AB049A (tag_id), add constraint FKDC8BC8BCE3AB049A foreign key (tag_id) references TAG_LABELS (id);
update OPERATOR_CONFIG set LABEL = '=' where DATA_TYPE= 'MULTIVAL' and OPERATOR_KEY = 'equals_unordered';
