alter table APPLICATION_USER add created_date timestamp;
alter table APPLICATION_USER add last_updated_by bigint;
alter table APPLICATION_USER add last_updated timestamp;
alter table APPLICATION_USER add created_by bigint;
alter table APPLICATION_USER add displayname varchar(255);
alter table APPLICATION_USER add hide_splash boolean;
alter table APPLICATION_USER add last_logged_time bigint;
alter table APPLICATION_USER add auth_handler_id bigint;
alter table APPLICATION_USER add email varchar(255);
alter table DEVELOPMENT_ENTITIES add extended_desc text;
alter table SUPER_APPLICATION_USER add created_date timestamp;
alter table SUPER_APPLICATION_USER add last_updated_by bigint;
alter table SUPER_APPLICATION_USER add last_updated timestamp;
alter table SUPER_APPLICATION_USER add created_by bigint;
alter table SUPER_APPLICATION_USER add displayname varchar(255);
alter table SUPER_APPLICATION_USER add hide_splash boolean;
alter table SUPER_APPLICATION_USER add last_logged_time bigint;
alter table SUPER_APPLICATION_USER add email varchar(255);
create table APP_USER_PROPERTIES ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, data_type varchar(255), prop_key varchar(255), super_user_id bigint, user_id bigint, prop_value varchar(255), primary key (id) );   
create table AUDIT_LOGS ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, component varchar(1000), hidden boolean, msgCode varchar(255), msgParams varchar(3000), primary key (id) );   
create table AUTH_HANDLER_REGISTRY ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, account_id varchar(255), config_data_json text, name varchar(255), type varchar(255), user_attrs_json text, primary key (id) );  
create table DEVELOPMENT_ENTITIES_TAGS ( dev_entity_id bigint not null, tag_id bigint not null, primary key (dev_entity_id, tag_id) );   
create table OPERATOR_CONFIG ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, data_type varchar(255), operator_key varchar(255), label varchar(255), primary key (id) );   
create table PM_ACTION_CONFIG ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, name varchar(255), short_code varchar(2), short_name varchar(50), plcy_model_id bigint, primary key (id) );   
create table PM_ATTRIBUTE_CONFIG ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, data_type varchar(255),name varchar(255), reg_ex_pattern varchar(255), short_name varchar(50), policy_model_id bigint, plcy_model_id bigint, primary key (id) );   
create table PM_ATTRIB_CONFIG_OPER_CONFIG ( attribute_id bigint not null, operator_id bigint not null, primary key (attribute_id, operator_id) );   
create table PM_OBLIGATION_CONFIG ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, name varchar(255), run_at varchar(255), short_name varchar(50), plcy_model_id bigint, primary key (id) );   
create table PM_PARAMETER_CONFIG ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, default_value varchar(1000), is_editable boolean, is_hidden boolean, list_values varchar(1000), is_mandatory boolean, name varchar(255), short_name varchar(50), data_type varchar(255), obligation_id bigint, primary key (id) );   
create table POLICY_MODEL ( discriminator varchar(31) not null, id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, description varchar(4000), name varchar(264), short_name varchar(50), status varchar(255), type varchar(255), primary key (id) );   
create table POLICY_MODEL_TAGS ( plcy_model_id bigint not null, tag_id bigint not null, primary key (plcy_model_id, tag_id) );   
create table SAVED_SEARCH ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, criteria_json varchar(4000), description varchar(255), lowercase_name varchar(255), name varchar(255), shared_mode varchar(255), status varchar(255), type varchar(255), primary key (id) );   
create table TAG_LABELS ( id bigint not null, created_date timestamp, last_updated_by bigint, last_updated timestamp, created_by bigint, version int4 not null, hidden boolean, tag_key varchar(255), label varchar(255), status varchar(255), type varchar(255), primary key (id) );
alter table APP_USER_PROPERTIES add constraint FK_779cewcdft7nk8geavqtp73vp foreign key (super_user_id) references SUPER_APPLICATION_USER;      
alter table APP_USER_PROPERTIES add constraint FK_dyfkd3c0my0v50dthairbf0v2 foreign key (user_id) references APPLICATION_USER;      
alter table DEVELOPMENT_ENTITIES_TAGS add constraint FK_8c1iyggwa0ox9r4webesww1cy foreign key (tag_id) references TAG_LABELS;      
alter table DEVELOPMENT_ENTITIES_TAGS add constraint FK_e27g95r7f2bwqcveaelp6vkp6 foreign key (dev_entity_id) references DEVELOPMENT_ENTITIES;     
alter table PM_ACTION_CONFIG add constraint FK_126fxoqmn30ytbi68gbugw8ij foreign key (plcy_model_id) references POLICY_MODEL;      
alter table PM_ATTRIBUTE_CONFIG add constraint FK_efpn3pjo8rgu1leddf1yjct6 foreign key (policy_model_id) references POLICY_MODEL;      
alter table PM_ATTRIBUTE_CONFIG add constraint FK_huf9agymbrkr0k059t5vwyebs foreign key (plcy_model_id) references POLICY_MODEL;      
alter table PM_ATTRIB_CONFIG_OPER_CONFIG add constraint FK_dnu63k3eq3p8k43rpk7hp6hgu foreign key (operator_id) references OPERATOR_CONFIG;      
alter table PM_ATTRIB_CONFIG_OPER_CONFIG add constraint FK_b15tsowx3866c7hw1bw30738e foreign key (attribute_id) references PM_ATTRIBUTE_CONFIG;      
alter table PM_OBLIGATION_CONFIG add constraint FK_4g7tsbo2rm29d6yu5520et90j foreign key (plcy_model_id) references POLICY_MODEL;      
alter table PM_PARAMETER_CONFIG add constraint FK_e9w3vpb9gghd1rp88pkyfxit1 foreign key (obligation_id) references PM_OBLIGATION_CONFIG;      
alter table POLICY_MODEL_TAGS add constraint FK_lb3jcfehky2ehtfr150tcf4hd foreign key (tag_id) references TAG_LABELS;     
alter table POLICY_MODEL_TAGS add constraint FK_66yjibu7osyrxc29fslttfdj2 foreign key (plcy_model_id) references POLICY_MODEL;
update OPERATOR_CONFIG set LABEL = '=' where DATA_TYPE= 'MULTIVAL' and OPERATOR_KEY = 'equals_unordered';
