#!/bin/bash
#
# DESCRIPTION
#	Invoke release build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR2=<path>
#		export BUILD_NUMBER=<#>
#		source setEnv
#		./buildRelease
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	export NLEXTERNALDIR2=c:/hudson/jobs/source_main_external/workspace
#	source setEnv
#	./buildRelease
#
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

export ANT_HOME=$NLEXTERNALDIR2/apache-ant/apache-ant-1.7.0

ANT=$ANT_HOME/bin/ant
LOG_FILE=buildRelease.log
BUILD_MANIFEST_FILE=build.manifest

(
set -x
# Extract Perforce Workspace and Hudson info (only if running on Hudson)
if [ -f ../config.xml ]; then
	scripts/getPerforceWorkspace.pl ../config.xml
fi

# Prepare environment
./configure --type=release || exit $?
source build.config

# Prepare dependencies
$ANT -f scripts/build_xlib.xml || exit $?

# Compile code and build installers
export ANT_OPTS="-Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=512m"
export ANT_ARGS="-Dexternal.dir=$NLEXTERNALDIR2 -Dversion_str=$VERSION_STR -Dversion_build_short=$VERSION_BUILD_SHORT -Dbuild_date_long=$BUILD_DATE_LONG"
$ANT -f src/build.xml buildOnly || exit $?

# Publish installers and artifacts
$ANT -f scripts/build_publish.xml archive || exit $?

# Create and publish build manifest
scripts/createBuildManifest.pl $LOG_FILE > $BUILD_MANIFEST_FILE || exit $?
$ANT -f scripts/build_publish.xml manifest || exit $?

set +x

echo
echo
echo "####################### BUILD MANIFEST CONTENTS ########################"
cat ${WORKSPACE}/${BUILD_MANIFEST_FILE}
echo "########################################################################"
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
