#!/bin/bash
#
# DESCRIPTION
#	Invoke PCV build
#
# USAGE:
#	Steps to invoke this script.
#		export NLEXTERNALDIR=<path>
#		source setEnv
#		./buildPcv
#
# HUDSON BUILD:
#	cd $WORKSPACE
#	source setEnv
#	./buildPcv
#	
# DEBUG:
#	To debug ANT problems, add -v option to an ANT command. For example:
#		$ANT -v -f scripts/build_xlib.xml

export ANT_HOME=$NLEXTERNALDIR2/apache-ant/apache-ant-1.7.0

ANT=$ANT_HOME/bin/ant
LOG_FILE=runUnitTest.log

(
set -x
# Prepare environment
./configure --type=pcv_smdc || exit $?
source build.config

# Prepare dependencies
$ANT -f scripts/build_xlib.xml || exit $?
#scripts/checkBuildLog.pl $LOG_FILE || exit $?

#  Compile code and build installers
export ANT_OPTS="-Xmx1024M -XX:PermSize=128m -XX:MaxPermSize=512m"
export ANT_ARGS="-Dexternal.dir=$NLEXTERNALDIR2 -Dversion_str=$VERSION_STR -Dversion_build_short=$VERSION_BUILD_SHORT -Dbuild_date_long=$BUILD_DATE_LONG"
$ANT -f src/build.xml buildAndTestAll || exit $?
#$ANT -f scripts/build_compile.xml || exit $?
#scripts/checkBuildLog.pl $LOG_FILE || exit $?

set +x
) 2>&1 | tee $LOG_FILE

exit ${PIPESTATUS[0]}
