package com.bluejungle.pf.engine.destiny;

/*
 * All sources, binaries and HTML pages (C) Copyright 2006 by Blue Jungle Inc,
 * Redwood City, CA. Ownership remains with Blue Jungle Inc.
 * All rights reserved worldwide.
 *
 * @author sasha, sergey
 *
 * @version $Id: //depot/Destiny/D_Nimbus/release/8.1/main/src/client/pf/src/java/test/com/bluejungle/pf/engine/destiny/AgentSuite.java#1 $
 */


import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;

import sun.misc.BASE64Decoder;
import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

import com.bluejungle.pf.domain.destiny.resource.AgentResourceManagerTest;


/**
 * This suite tests the agent side of PF.
 */
public class AgentSuite {

    public static Test suite() {
        TestSuite suite = new TestSuite("Test for com.bluejungle.pf.engine.destiny.test");
        //$JUnit-BEGIN$
        suite.addTest( new TestCase("Suite prepare") {
            protected void runTest() throws Exception {
                File exeFile = new File("c:\\small.exe");
                FileOutputStream fos = new FileOutputStream(exeFile);
                BASE64Decoder dec = new BASE64Decoder();
                dec.decodeBuffer(new ByteArrayInputStream(SMALL_EXE_UUE.getBytes()), fos);
                fos.close();
            }
        });
        suite.addTestSuite(AgentPolicyAssemblyTest.class);
        suite.addTestSuite(AgentPolicyContainerTest.class);        
        //FIXME some process is locking the cache file so the test can't continue.
        // suite.addTestSuite(AgentResourceManagerTest.class);
        suite.addTestSuite(BundleVaultImplTest.class);
        suite.addTest( new TestCase("Suite cleanup.") {
            protected void runTest() throws Exception {
                new File("c:\\small.exe").delete();
            }
        });
        //$JUnit-END$
        return suite;
    }

    private static final String SMALL_EXE_UUE =
        "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAA4AAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v\r\n"
    +   "ZGUuDQ0KJAAAAAAAAADU1xAjkLZ+cJC2fnCQtn5wE74jcJK2fnCQtn9wg7Z+cJW6I3CTtn5wlbpx\r\n"
    +   "cJG2fnCVuiFwnbZ+cJW6HnCStn5wlbokcJG2fnBSaWNokLZ+cAAAAAAAAAAAAAAAAAAAAABQRQAA\r\n"
    +   "TAEDAMB59EQAAAAAAAAAAOAADwELAQcKAAQAAAAGAAAAAAAAAxAAAAAQAAAAIAAAAABAAAAQAAAA\r\n"
    +   "AgAABAAAAAAAAAAEAAAAAAAAAABAAAAABAAAAAAAAAMAAAAAABAAABAAAAAAEAAAEAAAAAAAABAA\r\n"
    +   "AAAAAAAAAAAAAOQgAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIggAABIAAAAAAAAAAAAAAAAIAAAVAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAA4gIAAAAQAAAABAAAAAQAAAAAAAAAAAAAAAAAACAAAGAu\r\n"
    +   "cmRhdGEAAJwCAAAAIAAAAAQAAAAIAAAAAAAAAAAAAAAAAABAAABALmRhdGEAAAA0AAAAADAAAAAC\r\n"
    +   "AAAADAAAAAAAAAAAAAAAAAAAQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADPA\r\n"
    +   "w2ooaFggQADodQIAADP/V/8VACBAAGaBOE1adR+LSDwDyIE5UEUAAHUSD7dBGD0LAQAAdB89CwIA\r\n"
    +   "AHQFiX3k6yeDuYQAAAAOdvIzwDm5+AAAAOsOg3l0DnbiM8A5uegAAAAPlcCJReSJffxqAf8VNCBA\r\n"
    +   "AFmDDSwwQAD/gw0wMEAA//8VMCBAAIsNJDBAAIkI/xUsIEAAiw0gMEAAiQihSCBAAIsAoygwQADo\r\n"
    +   "LwEAAOjKAQAAOT0QMEAAdQxogBJAAP8VJCBAAFnonwEAAGgMMEAAaAgwQADoigEAAGgkEkAA6OYA\r\n"
    +   "AAChHDBAAIlF3I1F3FD/NRgwQACNReBQjUXYUI1F1FD/FRwgQACDxCCJRcw7x30IagjohQAAAFlo\r\n"
    +   "BDBAAGgAMEAA6DsBAAD/FRQgQACLTeCJCP914P912P911Oi6/v//g8QUi/CJdcg5feR1B1b/FRAg\r\n"
    +   "QAD/FQwgQADrLYtF7IsIiwmJTdBQUegpAAAAWVnDi2Xoi3XQg33kAHUHVv8VKCBAAP8VTCBAAINN\r\n"
    +   "/P+LxuglAQAAw8z/JQggQAD/JRggQACDPTAwQAD/dQb/JUAgQABoLDBAAGgwMEAA/3QkDOgMAQAA\r\n"
    +   "g8QMw/90JATo0f////fYG8D32FlIw2oMaGggQADomAAAAMdF5NggQACBfeTYIEAAcyKDZfwAi0Xk\r\n"
    +   "iwCFwHQL/9DrBzPAQMOLZeiDTfz/g0XkBOvV6JwAAADDagxoeCBAAOhUAAAAx0Xk4CBAAIF95OAg\r\n"
    +   "QABzIoNl/ACLReSLAIXAdAv/0OsHM8BAw4tl6INN/P+DReQE69XoWAAAAMP/JSAgQABoAAADAGgA\r\n"
    +   "AAEA6F8AAABZWcMzwMPMaNASQABkoQAAAABQi0QkEIlsJBCNbCQQK+BTVleLRfiJZehQi0X8x0X8\r\n"
    +   "/////4lF+I1F8GSjAAAAAMOLTfBkiQ0AAAAAWV9eW8lRw/8lOCBAAP8lPCBAAP8lRCBAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6IgAA\r\n"
    +   "AAAAAIYhAACUIQAAniEAAKYhAAC2IQAAxCEAANQhAADgIQAAfiEAAAQiAAAUIgAAIiIAADQiAABU\r\n"
    +   "IgAAYiIAAGwiAAD0IQAAdCEAAAAAAAAAAAAA/////2IRQAB2EUAAAAAAAP////8NEkAAERJAAAAA\r\n"
    +   "AAD/////URJAAFUSQAAAAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAFDBAANAgQAABAAAA0BIAAAAAAAAAAAAAAAAAAAAAAAAoIQAA\r\n"
    +   "AAAAAAAAAABIIgAACCAAACAhAAAAAAAAAAAAAI4iAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB6\r\n"
    +   "IgAAAAAAAIYhAACUIQAAniEAAKYhAAC2IQAAxCEAANQhAADgIQAAfiEAAAQiAAAUIgAAIiIAADQi\r\n"
    +   "AABUIgAAYiIAAGwiAAD0IQAAdCEAAAAAAADKAF9jX2V4aXQA+gBfZXhpdABLAF9YY3B0RmlsdGVy\r\n"
    +   "AM0AX2NleGl0AACXAmV4aXQAAHwAX19wX19faW5pdGVudgDCAF9hbXNnX2V4aXQAAG4AX19nZXRt\r\n"
    +   "YWluYXJncwA/AV9pbml0dGVybQCfAF9fc2V0dXNlcm1hdGhlcnIAALsAX2FkanVzdF9mZGl2AACC\r\n"
    +   "AF9fcF9fY29tbW9kZQAAhwBfX3BfX2Ztb2RlAACcAF9fc2V0X2FwcF90eXBlAADxAF9leGNlcHRf\r\n"
    +   "aGFuZGxlcjMAAE1TVkNSNzEuZGxsAGsAX19kbGxvbmV4aXQAuAFfb25leGl0ANsAX2NvbnRyb2xm\r\n"
    +   "cAAAdwFHZXRNb2R1bGVIYW5kbGVBAABLRVJORUwzMi5kbGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAEAAABO5kC7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\r\n"
    +   "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
}
