<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
					xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
					xmlns:xsd="http://www.w3.org/2001/XMLSchema"
					xmlns:bindings="http://nextlabs.com/destiny/bindings/log/v4"
					xmlns:tns="http://nextlabs.com/destiny/services/log/v4" 
					targetNamespace="http://nextlabs.com/destiny/services/log/v4" 
					name="LogService">

	<wsdl:import 	namespace="http://nextlabs.com/destiny/bindings/log/v4" 
					location="../bindings/LogServiceBindings.v4.wsdl"/> 
			
	<wsdl:service name="LogService.v4">
		<wsdl:port name="LogServiceIFPort.v4" binding="bindings:LogServiceIFBinding">
			<soap:address location="http://localhost:8080/dabs/services/LogServiceIFPort.v4"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
