/*
 * Created on Dec 12, 2007
 * 
 * All sources, binaries and HTML pages (C) copyright 2004-2007 by NextLabs, Inc.,
 * San Mateo CA, Ownership remains with NextLabs, Inc., All rights reserved
 * worldwide.
 */
package com.bluejungle.destiny.tools.dbinit.profiling;
/**
 * @author hchan
 * @version $Id: //depot/Destiny/D_Nimbus/release/8.1/main/src/server/tools/dbinit/src/java/test/com/bluejungle/destiny/tools/dbinit/profiling/ProfileKey.java#1 $
 */

enum ProfileKey{
	UNMAPPED_TYPE, MAPPED_TYPE,
	
	EXECUTED_TEST,
	
	DEFAULT_TRY_LENGTH,
	DEFAULT_TRY_DECIMAL,
	
	LENGTH, 
	DECIMAL,
	RETURNED_TYPE_CODE,
	
	PRIMARY_IMPLY_INDEX, 
	PRIMARY_IMPLY_UNIQUE, 
	UNIQUE_IMPLY_INDEX,
	
	MAX_TRIED_OPEN_CONNECTION,
	DEFAULT_TRY_CONNECTION,
	
	DROP_DNE_TABLE_CAUSE_EXCEPTION,
	DROP_DNE_COLUMN_CAUSE_EXCEPTION,
	DROP_DNE_CONSTRAINT_CAUSE_EXCEPTION,
	
	CAN_CREATE_EMPTY_TABLE,
	
	CAN_REDUCE_COLUMN_LENGTH,
	CAN_REDUCE_COLUMN_LENGTH_WITH_DATA_TRUNCATION,
	
	
	//the following key should be from query
	DATABASE_MAJOR_VERSION,
	DATABASE_MINOR_VERSION,
	DATABASE_PRODUCT_NAME,
	DATABASE_PRODUCT_VERSION,
	DRIVER_MAJOR_VERSION,
	DRIVER_MINOR_VERSION,
	DRIVER_NAME,
	DRIVER_VERSION,
	EXTRA_NAME_CHARACTERS,
	JDBC_MAJOR_VERSION,
	JDBC_MINOR_VERSION,
	MAX_CATALOG_NAME_LENGTH,
	MAX_CONNECTIONS,
	MAX_TABLE_NAME_LENGTH,
	MAX_USER_NAME_LENGTH,
	SQL_KEYWORDS,
	
	STORES_LOWER_CASE_IDENTIFIERS,
	STORES_LOWER_CASE_QUOTED_IDENTIFIERS,
	STORES_MIXED_CASE_IDENTIFIERS,
	STORES_MIXED_CASE_QUOTED_IDENTIFIERS,
	STORES_UPPER_CASE_IDENTIFIERS,
	STORES_UPPER_CASE_QUOTED_IDENTIFIERS,
	SUPPORTS_ALTER_TABLE_WITH_ADD_COLUMN,
	SUPPORTS_ALTER_TABLE_WITH_DROP_COLUMN,
	SUPPORTS_BATCH_UPDATES,
	SUPPORTS_NON_NULLABLE_COLUMNS,
	
	DUMMY,
	;

	@Override
	public String toString() {
		return this.name();
	}
}