package com.bluejungle.destiny.tools.dbinit.hibernate.mapping;

/**
 * TODO description
 *
 * @author hchan
 * @date Jun 28, 2007
 */
public enum FieldType {
	AGGREGATE, CAST, COLUMN, CONSTRAINT, CONSTRAINT_TRIGGER, CONVERSION, DATABASE, DOMAIN, 
	FOREIGN_KEY, FUNCTION, GROUP, INDEX, LANGUAGE, OPERATOR, OPERATOR_CLASS, PRIMARY_KEY, 
	RULE, SCHEMA, SEQUENCE, TABLE, TABLESPACE, TRIGGER, TYPE, USER, UNIQUE, VIEW, 
	UNKNOWN
}
