<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://bluejungle.com/destiny/services/user_preferences/v1" 
				  xmlns:tns="http://bluejungle.com/destiny/services/user_preferences/v1"
				  xmlns:bindings="http://bluejungle.com/destiny/bindings/user_preferences/v1"
				  xmlns:xs="http://www.w3.org/1999/XMLSchema" 
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">

   <wsdl:import namespace="http://bluejungle.com/destiny/bindings/user_preferences/v1" location="../bindings/UserPreferencesBindings.v1.wsdl"/> 
   
   <wsdl:service name="UserPreferencesService">
      <wsdl:port binding="bindings:UserPreferencesIFBinding" name="UserPreferencesService">
         <soap:address location="http://localhost:8080/dac/services/UserPreferencesService"/>
      </wsdl:port>
   </wsdl:service>

</wsdl:definitions>
